export const API_ENDPOINTS = {
  REQUEST_OTP: '/auth/customer/request-otp',
  VERIFY_OTP: '/auth/customer/verify-otp',
  CUSTOMER_ME: '/customer/me',
  ADDRESS: '/customer/addresses',
  PRODUCT: '/search/products',
  CART: '/cart',
  CUSTOMER_ORDER: '/customer/orders',
  CUSTOMER_ORDER_CANCEL: '/customer/orders/:orderId/cancel',
  CUSTOMER_ORDER_CONFIRM: '/customer/orders/:orderId/confirm',
  SUBSCRIPTION: '/customer/subscriptions',
  SUBSCRIPTION_PREVIEW_CALCULATE: '/customer/subscriptions/preview',
  NOTIFICATION_REGISTER: '/tokens/register',
  SUPPORT_TICKET: '/customer/support-tickets',
  WALLET_PAYMENTS: '/customer/wallet/payments',
  WALLET_TRANSACTIONS: '/customer/wallet/payments/transactions',
};
