/**
 * Address Type
 *
 * Represents a user's saved address for delivery or other purposes.
 * Includes geographical coordinates for map integration and location-based features.
 * The 'location' object provides additional context, such as city/area name.
 * 'isDefault' indicates if this is the primary address for the user.
 * All fields are required as they are essential for address functionality.
 */
export type Address = {
  id: string;
  label: string;
  address: string;
  pincode: string;
  location: {
    id: string;
    name: string;
  };
  lng: number;
  lat: number;
  isDefault: boolean;
};

/**
 * CreateAddressData Type
 *
 * Data structure for creating a new address.
 * Similar to Address but excludes 'id' (generated by server) and 'location' (derived from coordinates).
 * Includes 'city' and 'state' explicitly, as they may be separate from location.name.
 * 'isDefault' is optional, defaulting to false if not provided.
 * Used in forms and API requests for address creation.
 */
export type CreateAddressData = {
  label: string;
  address: string;
  pincode: string;
  city: string;
  state: string;
  lng: number;
  lat: number;
  isDefault?: boolean;
};

/**
 * AddressFormProps Interface
 *
 * Props for the AddressForm component.
 * 'address' is optional; if provided, form is in edit mode, else add mode.
 * 'onSave' callback receives validated form data for processing.
 * 'onCancel' closes the form without saving.
 * 'isPending' indicates loading state during save operation, used to disable form.
 */
export interface AddressFormProps {
  address?: Address;
  onSave: (data: CreateAddressData) => void;
  onCancel: () => void;
  isPending: boolean;
}

/**
 * AddressFormState Interface
 *
 * Internal state for the address form managed by useAddressForm hook.
 * Mirrors form fields for controlled inputs.
 * 'addressText' is the full address string, separate from structured fields.
 * Coordinates (lng, lat) are updated via map interactions.
 * Used to maintain form data and validation state.
 */
export interface AddressFormState {
  label: string;
  addressText: string;
  pincode: string;
  city: string;
  lng: number;
  lat: number;
  state: string;
}

/**
 * AddressMapSectionProps Interface
 *
 * Props for the AddressMapSection component, which displays an interactive map.
 * 'lat' and 'lng' set the initial map center and marker position.
 * 'onRegionChangeComplete' callback fired when user pans/zooms the map, updating coordinates.
 * 'region' type is 'any' due to React Native Maps library's complex region object.
 */
export interface AddressMapSectionProps {
  lat: number;
  lng: number;
  onRegionChangeComplete: (region: any) => void;
}

/**
 * AddressTabsProps Interface
 *
 * Props for AddressTabs component, allowing selection of address label (e.g., Home, Work).
 * 'label' is the current selected label.
 * 'onLabelChange' updates the label in the form state.
 * Provides predefined options for common address types.
 */
export interface AddressTabsProps {
  label: string;
  onLabelChange: (label: string) => void;
}

/**
 * AddressFormInputsProps Interface
 *
 * Props for AddressFormInputs component, handling text inputs for address details.
 * Includes address text, pincode, and state fields with their change handlers.
 * City is handled separately or derived from geocoding.
 * Ensures controlled input behavior for form validation.
 */
export interface AddressFormInputsProps {
  addressText: string;
  onAddressTextChange: (text: string) => void;
  pincode: string;
  onPincodeChange: (text: string) => void;
  state: string;
  onStateChange: (text: string) => void;
  addressError?: string | null;
}

/**
 * AddressGeocodeInfoProps Interface
 *
 * Props for AddressGeocodeInfo component, displaying geocoding results.
 * 'geocodeResult' contains reverse geocoding data (e.g., address from coordinates).
 * 'geocodeLoading' indicates if geocoding is in progress.
 * 'any' type for geocodeResult due to varying API response structures.
 * Helps users verify the address derived from map position.
 */
export interface AddressGeocodeInfoProps {
  geocodeResult: any;
  geocodeLoading: boolean;
}

/**
 * AddressCoordinatesDisplayProps Interface
 *
 * Props for AddressCoordinatesDisplay component, showing latitude and longitude.
 * Displays the current coordinates from map interactions.
 * Useful for debugging or confirming precise location.
 * Coordinates are in decimal degrees format.
 */
export interface AddressCoordinatesDisplayProps {
  lat: number;
  lng: number;
}
